# Generated by Django 3.2.5 on 2021-10-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='00000', max_length=50),
            preserve_default=False,
        ),
    ]
